### PR TITLE
Fix ipv6 netmask

### PR DESCRIPTION
**Pull request by luigibk**
- Ipv6 netmask for single address is /128
- Upgraded go to 1.17
- Some refactoring

### CODE REVIEW

**Comment by alec-pinson** [comment]
Not sure why it wont use the docker username and password from this repo...

**Comment by luigibk** [comment]
It builds ok ... I've also deployed it already :-)

**Comment by alec-pinson** [comment]
Cool. Hope my code wasn't too horrible 😉

**Comment by luigibk** [comment]
It works. Have a great weekend :-)

**Pull request merged**
